[package]
name = "atomex"
version = "0.1.1"
edition = "2024"

authors = ["lino <lino_snsalias@outlook.com>"]
description = "Atomics extensions in Rust"
repository = "https://github.com/ljsnogard/atomex-rs"
keywords = ["atomic", "traits"]
categories = ["algorithms", "no-std"]
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
support_u128_i128_atomics = []
default = []

[dependencies]
funty = { version = "3.0.0-rc2", default-features = false }
